### ISSUE TITLE
Evaluate cannot feed value of shape to tensor with shape 

### ISSUE THREAD

**Issue by HardwareToWebWizard** [Raj-08/tensorflow-object-contour-detection#2]
Hi,

as I wanted to try out your programm i did first train it. Then i wanted to evaluate my training after a few minutes. But as it wants to load the images into the feed_dict it says the following: 

```Cannot feed value of shape (500, 334, 3) for Tensor u'image_placeholder:0', which has shape '(1, ?, ?, 3)'```

I acutally fed the same images i used for training. What am i doing wrong here ?

**Comment by Raj-08** [comment]
just add an extra dimension to your image before feeding using 
import numpy as np
image = np.expand_dims(image,axis=0)

**Comment by HardwareToWebWizard** [comment]
okay thank you that worked. But now the eval.py saves numpy arrays in the save_preds directory ? Is this working as supposed ? How can i convert these numpy arrays into pictures ?
